name: OMine
version: '1.0-SNAPSHOT'
main: omine.OMine
api-version: '1.20'
depend:
  - Multiverse-Core
commands:
  mine:
    aliases: [ mines ]
  pickaxe:
    aliases: [ pick ]
  minecreate:
    aliases: [ minecriar ]